apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gitopsdemo
  name: gitopsdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitopsdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitopsdemo
    spec:
      containers:
      - image: ravibodireddi/employeeapp:latest
        name: gitopsdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gitopsdemo